// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AuthMessage.proto

package cn.xhzren.drama.proto;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuthMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AuthMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .AuthMessage.AuthType auth_type = 1;</code>
     * @return Whether the authType field is set.
     */
    boolean hasAuthType();
    /**
     * <code>required .AuthMessage.AuthType auth_type = 1;</code>
     * @return The authType.
     */
    cn.xhzren.drama.proto.Auth.AuthMessage.AuthType getAuthType();

    /**
     * <code>optional string content = 2;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <code>optional string content = 2;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>optional string time = 3;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>optional string time = 3;</code>
     * @return The time.
     */
    java.lang.String getTime();
    /**
     * <code>optional string time = 3;</code>
     * @return The bytes for time.
     */
    com.google.protobuf.ByteString
        getTimeBytes();
  }
  /**
   * Protobuf type {@code AuthMessage}
   */
  public  static final class AuthMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AuthMessage)
      AuthMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthMessage.newBuilder() to construct.
    private AuthMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthMessage() {
      authType_ = 0;
      content_ = "";
      time_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AuthMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              cn.xhzren.drama.proto.Auth.AuthMessage.AuthType value = cn.xhzren.drama.proto.Auth.AuthMessage.AuthType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                authType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              content_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              time_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.xhzren.drama.proto.Auth.internal_static_AuthMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.xhzren.drama.proto.Auth.internal_static_AuthMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.xhzren.drama.proto.Auth.AuthMessage.class, cn.xhzren.drama.proto.Auth.AuthMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code AuthMessage.AuthType}
     */
    public enum AuthType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNIVERSAL = 0;</code>
       */
      UNIVERSAL(0),
      /**
       * <code>NOT_TOKEN = 1;</code>
       */
      NOT_TOKEN(1),
      /**
       * <code>ACCOUNT_NOT_FOUNT = 2;</code>
       */
      ACCOUNT_NOT_FOUNT(2),
      /**
       * <code>ACCOUNT_INCORRECT = 3;</code>
       */
      ACCOUNT_INCORRECT(3),
      ;

      /**
       * <code>UNIVERSAL = 0;</code>
       */
      public static final int UNIVERSAL_VALUE = 0;
      /**
       * <code>NOT_TOKEN = 1;</code>
       */
      public static final int NOT_TOKEN_VALUE = 1;
      /**
       * <code>ACCOUNT_NOT_FOUNT = 2;</code>
       */
      public static final int ACCOUNT_NOT_FOUNT_VALUE = 2;
      /**
       * <code>ACCOUNT_INCORRECT = 3;</code>
       */
      public static final int ACCOUNT_INCORRECT_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static AuthType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static AuthType forNumber(int value) {
        switch (value) {
          case 0: return UNIVERSAL;
          case 1: return NOT_TOKEN;
          case 2: return ACCOUNT_NOT_FOUNT;
          case 3: return ACCOUNT_INCORRECT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AuthType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          AuthType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AuthType>() {
              public AuthType findValueByNumber(int number) {
                return AuthType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cn.xhzren.drama.proto.Auth.AuthMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final AuthType[] VALUES = values();

      public static AuthType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private AuthType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:AuthMessage.AuthType)
    }

    private int bitField0_;
    public static final int AUTH_TYPE_FIELD_NUMBER = 1;
    private int authType_;
    /**
     * <code>required .AuthMessage.AuthType auth_type = 1;</code>
     * @return Whether the authType field is set.
     */
    public boolean hasAuthType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .AuthMessage.AuthType auth_type = 1;</code>
     * @return The authType.
     */
    public cn.xhzren.drama.proto.Auth.AuthMessage.AuthType getAuthType() {
      @SuppressWarnings("deprecation")
      cn.xhzren.drama.proto.Auth.AuthMessage.AuthType result = cn.xhzren.drama.proto.Auth.AuthMessage.AuthType.valueOf(authType_);
      return result == null ? cn.xhzren.drama.proto.Auth.AuthMessage.AuthType.UNIVERSAL : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <code>optional string content = 2;</code>
     * @return Whether the content field is set.
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string content = 2;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 2;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object time_;
    /**
     * <code>optional string time = 3;</code>
     * @return Whether the time field is set.
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string time = 3;</code>
     * @return The time.
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string time = 3;</code>
     * @return The bytes for time.
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAuthType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, authType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, time_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, authType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.xhzren.drama.proto.Auth.AuthMessage)) {
        return super.equals(obj);
      }
      cn.xhzren.drama.proto.Auth.AuthMessage other = (cn.xhzren.drama.proto.Auth.AuthMessage) obj;

      if (hasAuthType() != other.hasAuthType()) return false;
      if (hasAuthType()) {
        if (authType_ != other.authType_) return false;
      }
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (!getTime()
            .equals(other.getTime())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAuthType()) {
        hash = (37 * hash) + AUTH_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + authType_;
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.xhzren.drama.proto.Auth.AuthMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xhzren.drama.proto.Auth.AuthMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xhzren.drama.proto.Auth.AuthMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xhzren.drama.proto.Auth.AuthMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xhzren.drama.proto.Auth.AuthMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xhzren.drama.proto.Auth.AuthMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xhzren.drama.proto.Auth.AuthMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.xhzren.drama.proto.Auth.AuthMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.xhzren.drama.proto.Auth.AuthMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.xhzren.drama.proto.Auth.AuthMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.xhzren.drama.proto.Auth.AuthMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.xhzren.drama.proto.Auth.AuthMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.xhzren.drama.proto.Auth.AuthMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AuthMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AuthMessage)
        cn.xhzren.drama.proto.Auth.AuthMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.xhzren.drama.proto.Auth.internal_static_AuthMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.xhzren.drama.proto.Auth.internal_static_AuthMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.xhzren.drama.proto.Auth.AuthMessage.class, cn.xhzren.drama.proto.Auth.AuthMessage.Builder.class);
      }

      // Construct using cn.xhzren.drama.proto.Auth.AuthMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        authType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.xhzren.drama.proto.Auth.internal_static_AuthMessage_descriptor;
      }

      @java.lang.Override
      public cn.xhzren.drama.proto.Auth.AuthMessage getDefaultInstanceForType() {
        return cn.xhzren.drama.proto.Auth.AuthMessage.getDefaultInstance();
      }

      @java.lang.Override
      public cn.xhzren.drama.proto.Auth.AuthMessage build() {
        cn.xhzren.drama.proto.Auth.AuthMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.xhzren.drama.proto.Auth.AuthMessage buildPartial() {
        cn.xhzren.drama.proto.Auth.AuthMessage result = new cn.xhzren.drama.proto.Auth.AuthMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.authType_ = authType_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.xhzren.drama.proto.Auth.AuthMessage) {
          return mergeFrom((cn.xhzren.drama.proto.Auth.AuthMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.xhzren.drama.proto.Auth.AuthMessage other) {
        if (other == cn.xhzren.drama.proto.Auth.AuthMessage.getDefaultInstance()) return this;
        if (other.hasAuthType()) {
          setAuthType(other.getAuthType());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000002;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000004;
          time_ = other.time_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAuthType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.xhzren.drama.proto.Auth.AuthMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.xhzren.drama.proto.Auth.AuthMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int authType_ = 0;
      /**
       * <code>required .AuthMessage.AuthType auth_type = 1;</code>
       * @return Whether the authType field is set.
       */
      public boolean hasAuthType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .AuthMessage.AuthType auth_type = 1;</code>
       * @return The authType.
       */
      public cn.xhzren.drama.proto.Auth.AuthMessage.AuthType getAuthType() {
        @SuppressWarnings("deprecation")
        cn.xhzren.drama.proto.Auth.AuthMessage.AuthType result = cn.xhzren.drama.proto.Auth.AuthMessage.AuthType.valueOf(authType_);
        return result == null ? cn.xhzren.drama.proto.Auth.AuthMessage.AuthType.UNIVERSAL : result;
      }
      /**
       * <code>required .AuthMessage.AuthType auth_type = 1;</code>
       * @param value The authType to set.
       * @return This builder for chaining.
       */
      public Builder setAuthType(cn.xhzren.drama.proto.Auth.AuthMessage.AuthType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        authType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .AuthMessage.AuthType auth_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        authType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 2;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string content = 2;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>optional string time = 3;</code>
       * @return Whether the time field is set.
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string time = 3;</code>
       * @return The time.
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string time = 3;</code>
       * @return The bytes for time.
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string time = 3;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string time = 3;</code>
       * @param value The bytes for time to set.
       * @return This builder for chaining.
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AuthMessage)
    }

    // @@protoc_insertion_point(class_scope:AuthMessage)
    private static final cn.xhzren.drama.proto.Auth.AuthMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.xhzren.drama.proto.Auth.AuthMessage();
    }

    public static cn.xhzren.drama.proto.Auth.AuthMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AuthMessage>
        PARSER = new com.google.protobuf.AbstractParser<AuthMessage>() {
      @java.lang.Override
      public AuthMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.xhzren.drama.proto.Auth.AuthMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021AuthMessage.proto\"\256\001\n\013AuthMessage\022(\n\ta" +
      "uth_type\030\001 \002(\0162\025.AuthMessage.AuthType\022\017\n" +
      "\007content\030\002 \001(\t\022\014\n\004time\030\003 \001(\t\"V\n\010AuthType" +
      "\022\r\n\tUNIVERSAL\020\000\022\r\n\tNOT_TOKEN\020\001\022\025\n\021ACCOUN" +
      "T_NOT_FOUNT\020\002\022\025\n\021ACCOUNT_INCORRECT\020\003B\035\n\025" +
      "cn.xhzren.drama.protoB\004Auth"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AuthMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AuthMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthMessage_descriptor,
        new java.lang.String[] { "AuthType", "Content", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
